# Use the official MariaDB 11.6 image
FROM mariadb:11.6

# Add image metadata in Open Container Format (OCF) compliant format
LABEL maintainer="Hochleitner, Wolfgang <wolfgang.hochleitner@fh-hagenberg.at>" \
      org.opencontainers.image.authors="Hochleitner, Wolfgang <wolfgang.hochleitner@fh-hagenberg.at>" \
      org.opencontainers.image.url="https://github.com/Digital-Media/fhooe-web-dock.git" \
      org.opencontainers.image.vendor="University of Applied Sciences Upper Austria, Department of Digital Media" \
      org.opencontainers.image.licenses="MIT License" \
      org.opencontainers.image.ref.name="fhooe-web-dock-db:latest" \
      org.opencontainers.image.title="fhooe-web-dock MariaDB" \
      org.opencontainers.image.description="MariaDB image of the fhooe-web-dock environment"

# Copy additional intialization scripts to the image
COPY src /src

# Run initialization scripts
RUN chmod 755 -- /src/*.sh \
    && /src/install-repository-tools.sh \
    && /src/install-cli-tools.sh
