# Linux x64 and MAC Intel and MAC M1
FROM phpmyadmin:5

LABEL maintainer="Hochleitner, Wolfgang <wolfgang.hochleitner@fh-hagenberg.at>" \
      org.opencontainers.image.authors="Hochleitner, Wolfgang <wolfgang.hochleitner@fh-hagenberg.at>" \
      org.opencontainers.image.url="https://github.com/Digital-Media/fhooe-web-dock.git" \
      org.opencontainers.image.vendor="University of Applied Sciences Upper Austria, Department of Digital Media" \
      org.opencontainers.image.licenses="MIT License" \
      org.opencontainers.image.ref.name="fhooe-web-dock-phpmyadmin:latest" \
      org.opencontainers.image.title="fhooe-web-dock phpMyAdmin" \
      org.opencontainers.image.description="phpMyAdmin Image of the fhooe-web-dock environment"

COPY src /src

# Install scripts
RUN cd /src \
    && chmod 755 *.sh \
    && /src/install-apt.sh \
    && /src/basic_tools.sh \
    && /src/switchhttps.sh
