# Linux x64
FROM php:8-apache

LABEL maintainer="mhteaching2703@gmail.com"

COPY src /src
# Install scripts
RUN docker-php-ext-install pdo_mysql \
    && /src/install-apt.sh \
    && /src/basic_tools.sh \
    && /src/install-PHP+Tools.sh \
	&& /src/install-Apache2.sh \
    && /src/switchhttps.sh
