# Use the official PHP 8.5-apache image
FROM php:8.5-apache

# Add image metadata in Open Container Format (OCF) compliant format
LABEL maintainer="Hochleitner, Wolfgang <wolfgang.hochleitner@fh-hagenberg.at>" \
      org.opencontainers.image.authors="Hochleitner, Wolfgang <wolfgang.hochleitner@fh-hagenberg.at>" \
      org.opencontainers.image.url="https://github.com/Digital-Media/fhooe-web-dock.git" \
      org.opencontainers.image.vendor="University of Applied Sciences Upper Austria, Department of Digital Media" \
      org.opencontainers.image.licenses="MIT License" \
      org.opencontainers.image.ref.name="fhooe-web-dock-php-apache:latest" \
      org.opencontainers.image.title="fhooe-web-dock Apache & PHP" \
      org.opencontainers.image.description="Apache & PHP image of the fhooe-web-dock environment"

# Copy additional intialization scripts to the image
COPY src /src

# Install additional packages and run initialization scripts
# RUN --mount provides PIE for xdebug install without adding it to the image
RUN --mount=type=bind,from=ghcr.io/php/pie:bin,source=/pie,target=/usr/local/bin/pie \
    mv "${PHP_INI_DIR}/php.ini-development" "${PHP_INI_DIR}/php.ini" \
    && apt-get update \
    && apt-get install -y --no-install-recommends curl \
                                                  gettext \
                                                  git \
                                                  iputils-ping \
                                                  less \
                                                  libfreetype6-dev \
                                                  libicu-dev \
                                                  libjpeg62-turbo-dev \
                                                  libpng-dev \
                                                  libpq-dev \
                                                  locales \
                                                  locales-all \
                                                  man-db \
                                                  nano \
                                                  net-tools \
                                                  openssl \
                                                  psmisc \
                                                  telnet \
                                                  unzip \
                                                  vim \
                                                  wget \
                                                  zip \
    && docker-php-ext-configure pgsql --with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pdo pdo_pgsql pgsql \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-configure intl \
    && docker-php-ext-install intl \
    && docker-php-ext-install gettext \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j"$(nproc)" gd \
    && docker-php-ext-install exif \
    && chmod 755 -- /src/*.sh \
    && pie install xdebug/xdebug \
    && /src/install-cli-tools.sh \
    && /src/install-php-tools.sh \
    && /src/configure-apache.sh \
    && /src/configure-https.sh \
    && rm -rf /var/lib/apt/lists/*

# Set environment variables
ENV LC_ALL=en_US.utf8 \
    LANG=en_US.utf8 \
    LANGUAGE=en_US.utf8