version: "3.9"

services:
  # MariaDB/MySQL Service
  db:
    build: 
      dockerfile: Dockerfile-mariadb
    container_name: mariadb
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql
    ports:
      - "6033:3306"
    # Values for environment variables are stored in .env file
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      LANG: ${LANG}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    # Apache/PHP Service
  php-apache:
    build: 
      dockerfile: Dockerfile-php
    container_name: webapp
    volumes:
      - ./webapp:/var/www/html
    ports:
      - "8080:80"
      - "7443:443"
    depends_on:
      - db
    # Values for environment variables are stored in .env file
    environment:
      DB_HOST: db:3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
  # phpMyAdmin Service
  phpmyadmin:
    build:
      dockerfile: Dockerfile-phpmyadmin
    container_name: pma
    ports:
      - "8082:80"
      - "8443:443"
    depends_on:
      - db
    # Values for environment variables are stored in .env file
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    restart: always

volumes:
  dbdata:

networks:
  default:
    name: webnet
